name: CI and CD to HuggingSpace

on:
  push:
    branches:
      - main

jobs:
  run_test_case:

    runs-on: ubuntu-latest
    env:
      # create 2 secrets in repo and load them here
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Set up Dependencies
        run: |
          make install

      - name: Test with pytest
        run: |
          make test

  # ref: https://docs.docker.com/guides/python/configure-github-actions/
  build_and_push_docker:

    runs-on: ubuntu-latest
    needs: run_test_case
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/chatbot_rag:latest
          platforms: linux/amd64

  push_HF_space:

    runs-on: ubuntu-latest
    needs: run_test_case
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # - name: Check large files
      #   uses: ActionsDesk/lfs-warning@v2.0
      #   with:
      #     filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://nblong:$HF_TOKEN@huggingface.co/spaces/nblong/chatbot main
